name: Build and Publish Odoo Fresh DB
on:
  push:
    branches:
      - master
      - BAH-1413
    paths:
      - ".github/workflows/build_publish_odoo_freshDB.yml"
      - "package/resources/odoo_clean_dump.sql"
      - "package/resources/setupDB.sql"
      - "package/docker/freshDB/**"
      - "package/docker/docker_publish.sh"

env:
  BAHMNI_VERSION: 0.94

jobs:
  docker-build-publish:
    name: Docker Build & Publish Odoo Fresh DB
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Odoo Modules Repo
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: ./package/docker/freshDB/docker_build.sh
      - name: Publish Docker Images
        run: ./package/docker/docker_publish.sh bahmni/odoo-10-db
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN}}
