name: Build and Publish Odoo
on:
  push:
    branches:
      - master
      - BAH-1413
    paths-ignore: 
      - '**.md'
  workflow_dispatch:
env:
  BAHMNI_VERSION: 0.94

jobs:
  docker-build-publish:
    name: Docker Build & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Odoo Modules Repo
        uses: actions/checkout@v2
      - name: Package
        run: zip -r package/resources/odoo-modules.zip . --exclude=*.git* --exclude="package/*"
      - name: Build Docker Image
        run: ./package/docker/scripts/docker_build_odoo.sh
      - name: List Docker Images
        run: docker images
      - name: Publish Docker Images
        run: ./package/docker/scripts/docker_publish_odoo.sh
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN}}
