name: Build and Publish
on:
  push:
    branches:
      - master
      - BAH-1413
    paths-ignore: 
      - '**.md'
  repository_dispatch:
    types: ["bahmni-scripts-trigger"]
  workflow_dispatch:
env:
  BAHMNI_VERSION: 0.94
  BRANCH_NAME: master
jobs:
  docker-build-publish:
    name: Docker Build & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Odoo Modules Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH_NAME }}
      - name: Package
        run: zip -r package/resources/odoo-modules.zip . --exclude=*.git* --exclude="package/*"
      - name: Extract DB Backup
        uses: actions/checkout@v2
        with:
          repository: Bahmni/bahmni-scripts
          ref: ${{ env.BRANCH_NAME }}
          path: bahmni-scripts
      - name: Build Docker Image
        run: ./package/docker/scripts/docker_build.sh
      - name: List Docker Images
        run: docker images
      - name: Publish Docker Images
        run: ./package/docker/scripts/docker_publish.sh
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN}}
